############## clock define##################

create_clock -period 20.000 -name ref_clk -waveform {0.000 10.000} [get_ports PL_CLK_50M]
set_property -dict {PACKAGE_PIN H16   IOSTANDARD LVCMOS33} [get_ports PL_CLK_50M]

############## key define ##################

set_property -dict {PACKAGE_PIN R19   IOSTANDARD LVCMOS33}  [get_ports PL_KEY1]
set_property -dict {PACKAGE_PIN T19   IOSTANDARD LVCMOS33}  [get_ports PL_KEY2]
set_property -dict {PACKAGE_PIN J15   IOSTANDARD LVCMOS33}  [get_ports PL_KEY3]
set_property -dict {PACKAGE_PIN B19   IOSTANDARD LVCMOS33}  [get_ports PL_KEY4]

############## LED define ##################

set_property -dict {PACKAGE_PIN G14   IOSTANDARD LVCMOS33} [get_ports PL_LED1]
set_property -dict {PACKAGE_PIN C20   IOSTANDARD LVCMOS33} [get_ports PL_LED2]
set_property -dict {PACKAGE_PIN B20   IOSTANDARD LVCMOS33} [get_ports PL_LED3]
set_property -dict {PACKAGE_PIN H17   IOSTANDARD LVCMOS33} [get_ports PL_LED4]

#################### HDMI 1 ########################

set_property -dict {PACKAGE_PIN K17   IOSTANDARD TMDS_33}  [get_ports HDMI1_CLK_P]
set_property -dict {PACKAGE_PIN K18   IOSTANDARD TMDS_33}  [get_ports HDMI1_CLK_N]
set_property -dict {PACKAGE_PIN G19   IOSTANDARD TMDS_33}  [get_ports HDMI1_D0_P]
set_property -dict {PACKAGE_PIN G20   IOSTANDARD TMDS_33}  [get_ports HDMI1_D0_N]
set_property -dict {PACKAGE_PIN F19   IOSTANDARD TMDS_33}  [get_ports HDMI1_D1_P]
set_property -dict {PACKAGE_PIN F20   IOSTANDARD TMDS_33}  [get_ports HDMI1_D1_N]
set_property -dict {PACKAGE_PIN D19   IOSTANDARD TMDS_33}  [get_ports HDMI1_D2_P]
set_property -dict {PACKAGE_PIN D20   IOSTANDARD TMDS_33}  [get_ports HDMI1_D2_N]
set_property -dict {PACKAGE_PIN F16   IOSTANDARD LVCMOS33} [get_ports HDMI1_HPD]
set_property -dict {PACKAGE_PIN M20   IOSTANDARD LVCMOS33} [get_ports HDMI1_OUT_EN]
set_property -dict {PACKAGE_PIN F17   IOSTANDARD LVCMOS33} [get_ports HDMI1_I2C_SCL]
set_property -dict {PACKAGE_PIN M19   IOSTANDARD LVCMOS33} [get_ports HDMI1_I2C_SDA]

#################### HDMI 2 ########################

set_property -dict {PACKAGE_PIN Y7   IOSTANDARD TMDS_33}  [get_ports HDMI2_CLK_P]
set_property -dict {PACKAGE_PIN Y6   IOSTANDARD TMDS_33}  [get_ports HDMI2_CLK_N]
set_property -dict {PACKAGE_PIN T5   IOSTANDARD TMDS_33}  [get_ports HDMI2_D0_P]
set_property -dict {PACKAGE_PIN U5   IOSTANDARD TMDS_33}  [get_ports HDMI2_D0_N]
set_property -dict {PACKAGE_PIN U7   IOSTANDARD TMDS_33}  [get_ports HDMI2_D1_P]
set_property -dict {PACKAGE_PIN V7   IOSTANDARD TMDS_33}  [get_ports HDMI2_D1_N]
set_property -dict {PACKAGE_PIN V8   IOSTANDARD TMDS_33}  [get_ports HDMI2_D2_P]
set_property -dict {PACKAGE_PIN W8   IOSTANDARD TMDS_33}  [get_ports HDMI2_D2_N]
set_property -dict {PACKAGE_PIN U8   IOSTANDARD LVCMOS33} [get_ports HDMI2_HPD]
set_property -dict {PACKAGE_PIN V5   IOSTANDARD LVCMOS33} [get_ports HDMI2_OUT_EN]
set_property -dict {PACKAGE_PIN V6   IOSTANDARD LVCMOS33} [get_ports HDMI2_I2C_SCL]
set_property -dict {PACKAGE_PIN W6   IOSTANDARD LVCMOS33} [get_ports HDMI2_I2C_SDA]

#################### MIPI CSI #############################

set_property -dict {PACKAGE_PIN Y9    IOSTANDARD LVDS} [get_ports LP_CLK_P]
set_property -dict {PACKAGE_PIN Y8    IOSTANDARD LVDS} [get_ports LP_CLK_N]
set_property -dict {PACKAGE_PIN Y12   IOSTANDARD LVDS} [get_ports LP_LANE0_P]
set_property -dict {PACKAGE_PIN Y13   IOSTANDARD LVDS} [get_ports LP_LANE0_N]
set_property -dict {PACKAGE_PIN V11   IOSTANDARD LVDS} [get_ports LP_LANE1_P]
set_property -dict {PACKAGE_PIN V10   IOSTANDARD LVDS} [get_ports LP_LANE1_N]
set_property -dict {PACKAGE_PIN U9    IOSTANDARD LVDS} [get_ports CAM_CLK]
set_property -dict {PACKAGE_PIN H17   IOSTANDARD LVDS} [get_ports CAM_GPIO]
set_property -dict {PACKAGE_PIN A20   IOSTANDARD LVDS} [get_ports CAM_SCL]
set_property -dict {PACKAGE_PIN E17   IOSTANDARD LVDS} [get_ports CAM_SDA]

#################### EEPROM #############################

#set_property PACKAGE_PIN V6 [get_ports EEPROM_I2C_SCL]
#set_property PACKAGE_PIN W6 [get_ports EEPROM_I2C_SDA]
set_property -dict {PACKAGE_PIN A20   IOSTANDARD LVCMOS33} [get_ports EEPROM_I2C_SCL]
set_property -dict {PACKAGE_PIN E17   IOSTANDARD LVCMOS33} [get_ports EEPROM_I2C_SDA]

############# GPIO_1P ##################

set_property -dict {PACKAGE_PIN N18   IOSTANDARD LVCMOS33} [get_ports GPIO1_0P]
set_property -dict {PACKAGE_PIN P19   IOSTANDARD LVCMOS33} [get_ports GPIO1_0N]
set_property -dict {PACKAGE_PIN N17   IOSTANDARD LVCMOS33} [get_ports GPIO1_1P]
set_property -dict {PACKAGE_PIN P18   IOSTANDARD LVCMOS33} [get_ports GPIO1_1N]
set_property -dict {PACKAGE_PIN N20   IOSTANDARD LVCMOS33} [get_ports GPIO1_2P]
set_property -dict {PACKAGE_PIN P20   IOSTANDARD LVCMOS33} [get_ports GPIO1_2N]
set_property -dict {PACKAGE_PIN T17   IOSTANDARD LVCMOS33} [get_ports GPIO1_3P]
set_property -dict {PACKAGE_PIN R18   IOSTANDARD LVCMOS33} [get_ports GPIO1_3N]
set_property -dict {PACKAGE_PIN T20   IOSTANDARD LVCMOS33} [get_ports GPIO1_4P]
set_property -dict {PACKAGE_PIN U20   IOSTANDARD LVCMOS33} [get_ports GPIO1_4N]
set_property -dict {PACKAGE_PIN V20   IOSTANDARD LVCMOS33} [get_ports GPIO1_5P]
set_property -dict {PACKAGE_PIN W20   IOSTANDARD LVCMOS33} [get_ports GPIO1_5N]
set_property -dict {PACKAGE_PIN Y18   IOSTANDARD LVCMOS33} [get_ports GPIO1_6P]
set_property -dict {PACKAGE_PIN Y19   IOSTANDARD LVCMOS33} [get_ports GPIO1_6N]
set_property -dict {PACKAGE_PIN Y16   IOSTANDARD LVCMOS33} [get_ports GPIO1_7P]
set_property -dict {PACKAGE_PIN Y17   IOSTANDARD LVCMOS33} [get_ports GPIO1_7N]
set_property -dict {PACKAGE_PIN W18   IOSTANDARD LVCMOS33} [get_ports GPIO1_8P]
set_property -dict {PACKAGE_PIN W19   IOSTANDARD LVCMOS33} [get_ports GPIO1_8N]
set_property -dict {PACKAGE_PIN U18   IOSTANDARD LVCMOS33} [get_ports GPIO1_9P]
set_property -dict {PACKAGE_PIN U19   IOSTANDARD LVCMOS33} [get_ports GPIO1_9N]
set_property -dict {PACKAGE_PIN V16   IOSTANDARD LVCMOS33} [get_ports GPIO1_10P]
set_property -dict {PACKAGE_PIN W16   IOSTANDARD LVCMOS33} [get_ports GPIO1_10N]
set_property -dict {PACKAGE_PIN V15   IOSTANDARD LVCMOS33} [get_ports GPIO1_11P]
set_property -dict {PACKAGE_PIN W15   IOSTANDARD LVCMOS33} [get_ports GPIO1_11N]
set_property -dict {PACKAGE_PIN W14   IOSTANDARD LVCMOS33} [get_ports GPIO1_12P]
set_property -dict {PACKAGE_PIN Y14   IOSTANDARD LVCMOS33} [get_ports GPIO1_12N]
set_property -dict {PACKAGE_PIN U14   IOSTANDARD LVCMOS33} [get_ports GPIO1_13P]
set_property -dict {PACKAGE_PIN U15   IOSTANDARD LVCMOS33} [get_ports GPIO1_13N]
set_property -dict {PACKAGE_PIN U13   IOSTANDARD LVCMOS33} [get_ports GPIO1_14P]
set_property -dict {PACKAGE_PIN V13   IOSTANDARD LVCMOS33} [get_ports GPIO1_14N]
set_property -dict {PACKAGE_PIN V12   IOSTANDARD LVCMOS33} [get_ports GPIO1_15P]
set_property -dict {PACKAGE_PIN W13   IOSTANDARD LVCMOS33} [get_ports GPIO1_15N]
set_property -dict {PACKAGE_PIN T12   IOSTANDARD LVCMOS33} [get_ports GPIO1_16P]
set_property -dict {PACKAGE_PIN U12   IOSTANDARD LVCMOS33} [get_ports GPIO1_16N]
set_property -dict {PACKAGE_PIN T11   IOSTANDARD LVCMOS33} [get_ports GPIO1_17P]
set_property -dict {PACKAGE_PIN T10   IOSTANDARD LVCMOS33} [get_ports GPIO1_17N]

############# GPIO_2P ##################

set_property -dict {PACKAGE_PIN J18   IOSTANDARD LVCMOS33} [get_ports GPIO2_0P]
set_property -dict {PACKAGE_PIN H18   IOSTANDARD LVCMOS33} [get_ports GPIO2_0N]
set_property -dict {PACKAGE_PIN G17   IOSTANDARD LVCMOS33} [get_ports GPIO2_1P]
set_property -dict {PACKAGE_PIN G18   IOSTANDARD LVCMOS33} [get_ports GPIO2_1N]
set_property -dict {PACKAGE_PIN K14   IOSTANDARD LVCMOS33} [get_ports GPIO2_2P]
set_property -dict {PACKAGE_PIN J14   IOSTANDARD LVCMOS33} [get_ports GPIO2_2N]
set_property -dict {PACKAGE_PIN H15   IOSTANDARD LVCMOS33} [get_ports GPIO2_3P]
set_property -dict {PACKAGE_PIN G15   IOSTANDARD LVCMOS33} [get_ports GPIO2_3N]
set_property -dict {PACKAGE_PIN J20   IOSTANDARD LVCMOS33} [get_ports GPIO2_4P]
set_property -dict {PACKAGE_PIN H20   IOSTANDARD LVCMOS33} [get_ports GPIO2_4N]
set_property -dict {PACKAGE_PIN L14   IOSTANDARD LVCMOS33} [get_ports GPIO2_5P]
set_property -dict {PACKAGE_PIN L15   IOSTANDARD LVCMOS33} [get_ports GPIO2_5N]
set_property -dict {PACKAGE_PIN K19   IOSTANDARD LVCMOS33} [get_ports GPIO2_6P]
set_property -dict {PACKAGE_PIN J19   IOSTANDARD LVCMOS33} [get_ports GPIO2_6N]
set_property -dict {PACKAGE_PIN K16   IOSTANDARD LVCMOS33} [get_ports GPIO2_7P]
set_property -dict {PACKAGE_PIN J16   IOSTANDARD LVCMOS33} [get_ports GPIO2_7N]
set_property -dict {PACKAGE_PIN L19   IOSTANDARD LVCMOS33} [get_ports GPIO2_8P]
set_property -dict {PACKAGE_PIN L20   IOSTANDARD LVCMOS33} [get_ports GPIO2_8N]
set_property -dict {PACKAGE_PIN L16   IOSTANDARD LVCMOS33} [get_ports GPIO2_9P]
set_property -dict {PACKAGE_PIN L17   IOSTANDARD LVCMOS33} [get_ports GPIO2_9N]
set_property -dict {PACKAGE_PIN M14   IOSTANDARD LVCMOS33} [get_ports GPIO2_10P]
set_property -dict {PACKAGE_PIN M15   IOSTANDARD LVCMOS33} [get_ports GPIO2_10N]
set_property -dict {PACKAGE_PIN N15   IOSTANDARD LVCMOS33} [get_ports GPIO2_11P]
set_property -dict {PACKAGE_PIN N16   IOSTANDARD LVCMOS33} [get_ports GPIO2_11N]
set_property -dict {PACKAGE_PIN P15   IOSTANDARD LVCMOS33} [get_ports GPIO2_12P]
set_property -dict {PACKAGE_PIN P16   IOSTANDARD LVCMOS33} [get_ports GPIO2_12N]
set_property -dict {PACKAGE_PIN R16   IOSTANDARD LVCMOS33} [get_ports GPIO2_13P]
set_property -dict {PACKAGE_PIN R17   IOSTANDARD LVCMOS33} [get_ports GPIO2_13N]
set_property -dict {PACKAGE_PIN V17   IOSTANDARD LVCMOS33} [get_ports GPIO2_14P]
set_property -dict {PACKAGE_PIN V18   IOSTANDARD LVCMOS33} [get_ports GPIO2_14N]
set_property -dict {PACKAGE_PIN T16   IOSTANDARD LVCMOS33} [get_ports GPIO2_15P]
set_property -dict {PACKAGE_PIN U17   IOSTANDARD LVCMOS33} [get_ports GPIO2_15N]
set_property -dict {PACKAGE_PIN T14   IOSTANDARD LVCMOS33} [get_ports GPIO2_16P]
set_property -dict {PACKAGE_PIN T15   IOSTANDARD LVCMOS33} [get_ports GPIO2_16N]
set_property -dict {PACKAGE_PIN P14   IOSTANDARD LVCMOS33} [get_ports GPIO2_17P]
set_property -dict {PACKAGE_PIN R14   IOSTANDARD LVCMOS33} [get_ports GPIO2_17N]
